Traceback (most recent call last):
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/miniconda3/envs/tf2/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
library(ggplot2)


df <- data.frame(
  sex=factor(rep(c("F", "M"), each=200)),
  weight=round(c(rnorm(200, mean=55, sd=5), rnorm(200, mean=65, sd=5)))
)

head(df)

# Basic histogram
ggplot(df, aes(x=weight)) + geom_histogram()
# Change the width of bins
ggplot(df, aes(x=weight)) + geom_histogram(binwidth=1)
# Change colors
p<-ggplot(df, aes(x=weight)) + geom_histogram(color="black", fill="white")
p
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [1], line 1[0m
[0;32m----> 1[0m [43mlibrary[49m(ggplot2)
[1;32m      4[0m df [38;5;241m<[39m[38;5;241m-[39m data[38;5;241m.[39mframe(
[1;32m      5[0m   sex[38;5;241m=[39mfactor(rep(c([38;5;124m"[39m[38;5;124mF[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mM[39m[38;5;124m"[39m), each[38;5;241m=[39m[38;5;241m200[39m)),
[1;32m      6[0m   weight[38;5;241m=[39m[38;5;28mround[39m(c(rnorm([38;5;241m200[39m, mean[38;5;241m=[39m[38;5;241m55[39m, sd[38;5;241m=[39m[38;5;241m5[39m), rnorm([38;5;241m200[39m, mean[38;5;241m=[39m[38;5;241m65[39m, sd[38;5;241m=[39m[38;5;241m5[39m)))
[1;32m      7[0m )
[1;32m      9[0m head(df)

[0;31mNameError[0m: name 'library' is not defined
NameError: name 'library' is not defined

